name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    strategy:
      matrix:
        php: ['8.1', '8.2']

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@2.9.0
        with:
          php-version: "${{ matrix.php }}"

      - name: Build extension
        run: |
          phpize
          ./configure
          make